# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            My LeetCode Journey
tagline:          'Lessons learned from grinding LeetCode problems'
description:      'Lessons learned from grinding LeetCode problems'
#url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Ran Huo'
  #url:            https://twitter.com/mdo

#paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/cnknd/leetcode


# pagination
pagination:
  enabled: true
  debug: false
  collections: 'posts'
  per_page: 5
  permalink: '/page/:num/'
  
#Plugins
plugins: [jekyll-paginate-v2, jekyll-gist]