theme: jekyll-theme-cayman

author:
  name:           'Ran Huo'

# site
title: 'My LeetCode Journey'
description: 'Lessons learned from grinding LeetCode problems'
baseurl: '/'

github:
  repo:           https://github.com/cnknd/leetcode

plugins:
  - jekyll-paginate
  - jekyll-sitemap